- shell: apt-get update -y && apt-get upgrade -y

- name: Install additional packages
  apt: package={{ item }} state=present
  with_items:
    - vim
    - apache2
    - mysql-server
    - mysql-client

- name: Add removable storage
  mount: src=/dev/sda1 name=/mnt/storage fstype=ext4 opts="defaults,noatime" dump=0 passno=1 state=mounted
